防具ごと透明化することができるタグEM_hideを作成
The-Chicken-Empire/EliteMobs pull request #18
Opened 2023-05-27 13:54 UTC by rukky321

透明化させたいモブに対してtag @s add EM_hide
解除したい時はtag @s remove EM_hide

2023-05-27 14:03 UTC, rukky321 commented
テストだと"EliteMobs/data/elite_mobs/functions/tags/hide/restore.mcfunction"の6行目は
ActiveEffects:[{Id:14b},{Amplifier:0b}]じゃないとダメらしいんだけど
実際に実行したらActiveEffects:[{Id:14},{Amplifier:0b}]じゃないとうまくいかなかった

2023-05-31 17:06 UTC, haiiro2gou requested changes

2023-05-31 17:06 UTC, haiiro2gou commented on EliteMobs/data/elite_mobs/functions/tags/hide/restore.mcfunction
> +execute if entity @s[nbt={ActiveEffects:[{Id:14},{Amplifier:0b}]}] run effect clear @s invisibility
```suggestion
execute if entity @s[nbt={ActiveEffects:[{Id:14b},{Amplifier:0b}]}] run effect clear @s invisibility
```
byte表記にしないとlinter君はうるさいです

2023-05-31 17:07 UTC, haiiro2gou commented on EliteMobs/data/elite_mobs/functions/tags/hide/restore.mcfunction
> +execute if entity @s[nbt={ActiveEffects:[{Id:14},{Amplifier:0b}]}] run effect clear @s invisibility
はてさてどうしたものか

2023-06-08 16:20 UTC, haiiro2gou commented
これでダメなのは本格的に1.20のlinter実装待ちかなぁ

2023-06-13 14:51 UTC, haiiro2gou commented on EliteMobs/data/elite_mobs/functions/tags/hide/restore.mcfunction
> +execute if entity @s[nbt={ActiveEffects:[{Id:14},{Amplifier:0b}]}] run effect clear @s invisibility
要らんな、よし！

2023-06-13 14:53 UTC, haiiro2gou approved these changes
多分ええやろ

2023-06-13 14:54 UTC, merged