強化ファントム
The-Chicken-Empire/EliteMobs pull request #19
Opened 2023-05-30 11:56 UTC by Nek0kan

強化したファントムを追加しました

2023-05-30 15:14 UTC, haiiro2gou requested changes

2023-05-30 15:14 UTC, haiiro2gou commented on EliteMobs/data/elite_mobs/functions/load.mcfunction
> +forceload add 0 0 0 0
```suggestion
scoreboard players set #4 constant 4
scoreboard players set #5 constant 5
forceload add 0 0 0 0
```

2023-05-30 15:14 UTC, haiiro2gou commented on EliteMobs/data/elite_mobs/functions/load.mcfunction
> +forceload add 0 0 0 0
消し飛ばしていらっしゃる

2023-05-30 23:10 UTC, rukky321 commented
一部のファイル位置がおかしいね
EliteMobs/data/elite_mobs...じゃなくてdata/elite_mobsになってるのがいくつかある

2023-05-31 00:12 UTC, rukky321 commented
耐久5つけるコマンドか体力回復のコマンドでも入れてる？
一回耐久3ダイヤフルが壊れるまで戦って、死んだ後に敵のHP見たら284だったんだが

2023-05-31 00:20 UTC, rukky321 commented
dragon_fireballで生成されるAECって負傷だからゾンビ形態の時に回復するじゃん
倒せるわけねえだろ

2023-06-01 08:23 UTC, closed without merging