アンデッドモンクの追加あと落下ダメージ無効化タグとScoreToHealth入れといたよ！
The-Chicken-Empire/EliteMobs pull request #28
Opened 2023-06-13 07:18 UTC by Nek0kan

アンデッドモンクの追加あと落下ダメージ無効化タグとScoreToHealth入れといたよ！

2023-06-13 15:17 UTC, haiiro2gou reviewed
ちょっとまだ何とも言えんでござる

2023-06-13 16:20 UTC, haiiro2gou requested changes
タグ回りがガバガバなんで修正しておいて

2023-06-13 16:35 UTC, haiiro2gou approved these changes
ぱっと見よさそう

2023-06-18 14:18 UTC, haiiro2gou commented
ところでScoreToHealthと/damage両方入れているので？

2023-06-18 14:19 UTC, Nek0kan commented
防具貫通ダメージと防具非貫通ダメージがあるため。以上

2023-06-18 14:25 UTC, haiiro2gou commented
貫通ダメは/damageコマンドで使えないのか
非貫通ダメを計算してScoreToHealthで使えないのか、という意味で聞いた

2023-06-20 08:24 UTC, merged